### PR TITLE
Another Shape (+demo link)

### PR DESCRIPTION
**Pull request by thani-sh**
Added a commonly required shape. Demo available here http://smartecharts.aftrix.com/carousel/index.html

### CODE REVIEW

**Comment by thani-sh** [comment]
Just FYI the reflections doesn't belong to the commit (it's just obvious right?).
The reflection thing comes from another jQ plugin. I had to tweak the roundabout js file; just a line to resize reflection.

**Comment by fredleblanc** [comment]
Wow man, this is great. Need to do some testing with it — so I may have questions. But great work!

**Comment by thani-sh** [comment]
You and your questions are welcome. Thanks for this plugin man, it's just awesome.

**Comment by haleeben** [comment]
I've been trying to get the reflection.js to work with roundabout.js but it is throwing off the image scale. The images at the back are bigger than the front, anyone got ant ideas no how to fix? Any help would be much appreciated, I'm still a novice with jQuery

**Comment by thani-sh** [comment]
Sorry bro I can't remember for sure but try this one. I think this is it.

> child
>  .css({
>    left: ((factors.x \* info.midStage.width + info.nudge.width) - factors.width / 2.0).toFixed(0) + "px",
>    top: ((factors.y \* info.midStage.height + info.nudge.height) - factors.height / 2.0).toFixed(0) + "px",
>    width: factors.width + "px",
>    height: factors.height + "px",
>    opacity: (info.opacity.min + (info.opacity.diff \* factors.scale)).toFixed(2),
>    zIndex: Math.round(info.zValues.min + (info.zValues.diff \* factors.z)),
>    fontSize: (factors.adjustedScale \* data.startFontSize).toFixed(1) + "px"
>  });
> child.find('canvas').css({
>    width: factors.width + "px",
>    height: factors.height/4 + "px",
>    opacity: (info.opacity.min + (info.opacity.diff \* factors.scale)).toFixed(2)/2,
> })

It comes around line number 492 on roundabout.js
The 'canvas' is the reflection part. This code updates the reflection size and opacity.

**Comment by MathieuUrstein** [comment]
Thank you so much

**Pull request closed without merging**
